---
title: "R Notebook"
output: html_notebook
---



```{r}
install.packages("tidyverse")
library(tidyverse)
```

```{r}
ggplot(baad_with_map, aes(mean_annual_precipitation, age, colour=vegetation)) + geom_point()
```
```{r}
ggplot(baad_with_map, aes(mean_annual_precipitation, h.t)) + geom_point()
```
```{r}
ggplot(baad_with_map, aes(mean_annual_precipitation, h.t, colour=growingCondition)) + geom_point()
```

```{r}
#dont know what this one means 
ggplot(baad_with_map, aes(mean_annual_precipitation, a.ssbh)) + geom_point()
```

```{r}
#dont know what this one means
ggplot(baad_with_map, aes(mean_annual_precipitation, c.d)) + geom_point()
```

```{r}
ggplot(baad_with_map, aes(mean_annual_precipitation, latitude)) + geom_point()
```
```{r}
ggplot(baad_with_map, aes(latitude, age)) + geom_point()
```

```{r}
ggplot(baad_with_map, aes(latitude, h.t)) + geom_point()
```
```{r}


```


```{r}
baad_with_map %>%
  group_by(species) %>%
  summarize(sample_size=n()) %>%
  arrange(desc(sample_size))
```

```{r}
leaflet(data = baad_with_map) %>%
    addTiles() %>%
    addCircleMarkers(lat = ~latitude, lng = ~longitude,popup = ~species)
```

```{r}
pal <- colorFactor(  palette = 'Dark2',  
                     domain = baad_with_map$studyName)
leaflet(data = baad_with_map) %>%  
  addTiles() %>%  
  addCircleMarkers(lat = ~latitude, lng = ~longitude,popup = ~species, color=~pal(studyName))
```


# loading tree height data



```{r}
library(raster)

tree_height<-raster("data/Scheffer_2018/90th_percentile_height.tif")
plot(tree_height)
```

cropping to just australia

```{r}
australia<-extent(c(111, 158, -44, -9.6))
tree_aus <- crop(tree_height,australia)
plot(tree_aus)
```


extract data


```{r}
library(tidyverse)
df<-tibble(
  tree_height=getValues(tree_aus)
)
xy<-coordinates(tree_aus)
df<-cbind(df,xy)
```


```{r}
prec<-getData('worldclim', var='prec', res=10)
map<-sum(prec)
plot(map)
```



```{r}
df<-mutate(df,annual_precip=raster::extract(map,xy))

filter(df,tree_height>0) %>%
ggplot(aes(x=annual_precip,y=tree_height))+geom_point()

```

trying quantile regression


```{r}



```

